### ISSUE TITLE
No styles for .Tab[data-discarded]

### ISSUE THREAD

**Issue by Dook1** [mbnuqw/sidebery#102]
There are no styles for .Tab[data-discarded]>.lvl-wrapper and .Tab[data-discarded] .title  in the settings.

**Comment by mbnuqw** [comment]
Yes, sorry about that, but I don't want to add more customizable CSS variables. There are too many different states of elements, and if I continue to add more custom variables, it will be hard to implement any changes in themes styles. Maybe later, when the structure of this addon will be more stable, I'll consider providing this and other styles in the custom variables section.

For now, instead of using variables, you can write your custom CSS.

**Comment by Dook1** [comment]
Я собственно так уже и сделал. A насчет приоритета - согласен.
