### ISSUE TITLE
Storage Completely Empty

### ISSUE THREAD

**Issue by Sorek** [mbnuqw/sidebery#1040]
This one has me stumped.  Export/Snapshot/Storage are all broken.  I go into about:debugging and Inspect.  Running browser.storage.local.get() throws a unable to clone error.

  Running browser.storage.local.get('tabsDataCache') gives an empty, and browser.storage.local.get('tabsData_v4') will just sit there doing nothing.  No promise, no error.

  If I click on the Storage tab it comes up empty. Nothing loads. Navigating to the extension folder in profile/storage/default reveals even the actual storage is just completely empty.

  The thing is otherwise it works fine!  I've got something like 4000 tabs (likely the root of the problem) but they're all indented and parented properly in their perspective panels.  If I close the browser or reboot everything is in it's proper place when it loads.

  I've tried digging through the code so I wouldn't have to bother but my typescript knowledge is too limited. I can just wipe it and start over but I thought I'd ask first.  Thanks for your time.

**Comment by mbnuqw** [comment]
Probably internally broken addon storage because v4 didn't set hard limits for snapshots and favicon cache. Possible workarounds:
- Remove sidebery, update `about:addons` page, install sidebery.
- Close Firefox, manually remove sidebery data (in profile dir: ./storage/default/moz-extension+++{some id, to get it, create group page and see it in url}^userContextId={some id}), open Firefox.
- Refresh Firefox profile
