### ISSUE TITLE
Dragging the tabs outside the Sidebery separates it into a new window

### ISSUE THREAD

**Issue by 0x42697262** [mbnuqw/sidebery#1054]
## Description

Does a feature exists for dragging tabs outside sidebery separating it into a new window? I know that right clicking and  selecting "move to new window" exists, however it would be nice to have it implemented. It's nice that I can drag the tab to another window sidebery, I did expect that would work.

Also a feature when you select the add-on icon rather than only having it appear on the side, allow it to have a floating window.

---

How can I help contribute to this feature? I'll try reading the code when I have the time. Thanks

**Comment by gxtu** [comment]
I was looking for this feature as well, because it's something I did all the time in Tree Style Tab. Maybe having a look at their implementation could help with making this possible in Sideberry as well.

Edit: The open in new window button also only applies to a single tab, not the whole tree, as one might expect.

**Comment by mbnuqw** [comment]
Available in the latest version, check Sidebery settings > Drag and drop > "Action on drag-and-drop to the outside of sidebar"
