### ISSUE TITLE
Minimise Tabs

### ISSUE THREAD

**Issue by yougotwill** [mbnuqw/sidebery#1070]
## Description

Not sure if this is possible but it would be awesome if we could "minimise" tabs to just their icons like on Brave and then the sidebar expands on hover or via a shortcut. Would save screen real-estate until we actually need to interact with the tabs

Example:

https://github.com/mbnuqw/sidebery/assets/14887287/6b30f12e-b2a2-41d6-8b2a-b0c502623b34

**Comment by emvaized** [comment]
It is not possible to do by this extension due to security limitations, but it is possible to do using [userChrome.css](https://www.reddit.com/r/FirefoxCSS/comments/73dvty/tutorial_how_to_create_and_livedebug_userchromecss/) Firefox modifications, like it's shown [here](https://www.reddit.com/r/FirefoxCSS/comments/obw2wm/edgestyle_vertical_tabs_for_firefox_with_tab/).
