### ISSUE TITLE
Wrong tab activated when switching tabs with ctrl-tab while WebRTC active 

### ISSUE THREAD

**Issue by msmol** [mbnuqw/sidebery#1148]
## Steps to reproduce
- Open Firefox in [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)
- Install Sidebery
- Add a second panel, and open multiple tabs in each of your 2 panels
- Set "Hide native tabs of inactive panel" to true
- Open any WebRTC (e.g. Google Meet) in a tab in the first panel
- Go to second panel and `ctrl-Tab` through your tabs

## Expected behavior
- `ctrl-Tab` while on the last tab of second panel should go back to top of second panel

## Actual behavior
- `ctrl-Tab` while on the last tab of second panel goes to the tab with the WebRTC session in the first panel

Using Sidebery v5.0.0rc4 (but issue existed in previous version as well)

**Comment by mbnuqw** [comment]
It's an API limitation of Firefox - ["Tabs that are sharing the screen, microphone or camera cannot be hidden."](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/hide)
The only workaround (detecting an incorrectly activated tab and switching to the first or last tab of the current panel) is too clumsy and annoying, since the user still sees the incorrect switching. Therefore, all I can suggest is to use Sidebery shortcuts instead of `Ctrl[+Shift]+Tab`.
