### ISSUE TITLE
What is the "window selection menu"?

### ISSUE THREAD

**Issue by mxmilkiib** [mbnuqw/sidebery#1149]
I see the General "Show screenshots in the window selection menu" setting, but I don't know how to access it.

I don't see anything in the keybindings or right click menu on tabs or the tab bar.

What am I missing?

Also, how to I access the tab group pages?

Thanks!

**Comment by Nionor** [comment]
On the first part I'm not sure, maybe it has something to do with the snapshot viewer.
But to access the tab group page just click on a tab group and you should land on a page looking something like this.
![image](https://github.com/mbnuqw/sidebery/assets/36626165/d8610967-1337-45c6-8a32-94cac9c59514)

**Comment by mbnuqw** [comment]
> I see the General "Show screenshots in the window selection menu" setting, but I don't know how to access it.

It's a popup of currently open windows that appears in the sidebar when you try to move selected tabs to "Window..." (option in context menu).

Turned off:
![screenshot-2023-08-05 15:02:08](https://github.com/mbnuqw/sidebery/assets/6276694/3cbeae3f-bd67-4f81-85d0-da83f60ad162)

Turned on:
![screenshot-2023-08-05 15:02:31](https://github.com/mbnuqw/sidebery/assets/6276694/20d58a68-0cbc-48c2-a95b-4cfecc6f0476)

It disabled by default because it needs additional permission.

---

> Also, how to I access the tab group pages?

@Nionor correctly answered this question.
