### ISSUE TITLE
Unable to drag tabs into bookmark folders

### ISSUE THREAD

**Issue by TheDukexx99** [mbnuqw/sidebery#1256]
Used to be able to drag tabs to bookmark folders now it gives a no symbol and won't allow it

**Comment by yump** [comment]
I also came to report this.  To clarify, what doesn't work is dragging from Sidebery's tab list panel to the native bookmark management window (ctrl+shift+O) or to the bookmarks toolbar.

Dragging a tab from Sidebery's tab list panel to Sidebery's bookmark panel works, as does dragging from Firefox's native tab list to Sidebery's bookmarks panel.  But I prefer to use the native bookmark manager because there's no way to have two sidebars open at once.

Dragging from Sidebery to the bookmark manager worked before the upgrade to v5.

**Comment by llc0930** [comment]
Dragging a tab from Sidebery's tab list panel to the native bookmark manager or to the bookmarks toolbar works normally here.

environment: `x11, firefox 115.2.1esr, sidebery v5.0.0`

**Comment by oscarus** [comment]
I had the same "issue," but it turns out it was caused by a the new feature that allows moving a tab to a new window by dragging it outside the sidebar.

The restore the previous behavior, I changed the setting under **drag and drop > action on drag-and-drop to the outside of sidebar > pass dragged data to the target**

**Comment by llc0930** [comment]
I have the same settings as mentioned in the comments above, I'm not sure what the defaults are now.

**Comment by mbnuqw** [comment]
Can't reproduce. Dropping the tabs into the native bookmark folder (in toolbar) or into the native "Library" window successfully creates new bookmarks (if the "Action on drag-and-drop..." set to "Pass dragged data to the target" or the Alt key was pressed before the drag).

Please, if you're experiencing this issue, provide more info: OS, Sidebery Debug info (Sidebery settings >> Help >> Show debug info)

**Comment by yump** [comment]
> I had the same "issue," but it turns out it was caused by a the new feature that allows moving a tab to a new window by dragging it outside the sidebar.
>
> The restore the previous behavior, I changed the setting under **drag and drop > action on drag-and-drop to the outside of sidebar > pass dragged data to the target**

This fixed it for me.

>(if the "Action on drag-and-drop..." set to "Pass dragged data to the target" or the Alt key was pressed before the drag)

It seems that pressing alt was not previously required.  If this is a new feature or a change to previous defaults, anyone who was using drag&drop with Sidebery v4 and was automatically updated to v5 will experience this as breakage.

**Comment by TheDukexx99** [comment]
Thank you wasn't aware of a new feature. I was able to restore the previous behavior by changing the drag and drop setting to pass dragged data to target

**Comment by llc0930** [comment]
> It seems that pressing alt was not previously required. If this is a new feature or a change to previous defaults, anyone who was using drag&drop with Sidebery v4 and was automatically updated to v5 will experience this as breakage.

Yes, I just remembered. When I updated from v4 to v5 I immediately checked every setting and at that time I did change the value of this feature.
