### ISSUE TITLE
PLEASE GO BACK TO BEFORE THE UPDATE 

### ISSUE THREAD

**Issue by axelromfelt** [mbnuqw/sidebery#1263]
## Description
WTF IS THIS UPDATE EVERYTHING LOOKS BAD, THE RIGHT CLICK MENU IS USELESS NOW PLEASE I BEG YOU MAKE SO YOU CAN USE THE CONTEXT MENU LIKE THIS NEW ONE IS USELESS THE OLD ONE ACTAULLY HAD A PURPOSE PLEASE I BEG YOU ALLOW ME TO CHANGE IT BACK

**Comment by AlexCzar** [comment]
You can easily do it if you backed up your sidebery data during v5 upgrade (I'm so happy, I did).
1. load your backup
2. uninstall sidebery
3. go to tags on github, find the latest v4, install the signed xpi.
4. disable auto-update for it
5. fix the groups manually (top level group page won't load because of different extension uuid)

**Comment by mbnuqw** [comment]
You can rollback to v4 (following @AlexCzar's instructions) or open a new issue[s] per problem (without capslock and with more details)
