### ISSUE TITLE
Context menu : new design in v5 or bug ?

### ISSUE THREAD

**Issue by Elaws** [mbnuqw/sidebery#1289]
Is this how the context menu supposed to look in v5 : 

![image](https://github.com/mbnuqw/sidebery/assets/52013479/b4d32609-6516-491d-ab6b-15dd887a5cb4)

If so, is there a way to revert to v4 design ? I prefer when everything was accessible in one click and had a more intuitive and visual design.

Moreother : 

- `Move to` > `New window` : nothing happens.
- `Move to` option does not allow to move to default panel (image below).
![image](https://github.com/mbnuqw/sidebery/assets/52013479/479ddd7c-1973-42ba-9d39-38930be91e6a)

Thank you.

**Comment by SpaceshipOperations** [comment]
First of all I want to thank the developers of this extension as it's been an invaluable addition to Firefox for a very long time for me.

That said, I do find the recent redesign of the context menu to be inconvenient, mainly because it hides the container buttons inside a submenu, and on top of that the menu does not automatically expand on hover - you have to click it in order to open it! IMHO having to click submenus inside a context menu in order to open them is an excruciating UX misfeature for anyone who isn't on a touch screen device, which I suppose is the majority of desktop users. Though the amount of inconvenience this brings might only manifest if you use the contents of the submenu a lot (which I think is the case with containers for a lot of people).

Fortunately the developers did provide a way out. In Sideberry's settings, scroll down to "Context menu", click "Edit context menu", then under the "Reopen in" section, you will find an entry named "Container..." which is a placeholder for the various containers you have. What you want to do is move this "Container..." entry to the unlabled section at the top (which contains four entries by default: "Undo close tab", "Mute", "Reload", and "Add to bookmarks"). The entries under this unlabled section show up as icon-only buttons at the top of the context menu, so placing the "Container..." placeholder there causes all of your container buttons to show up in this section, just as was the case in the old design.

**Comment by Faelights** [comment]
Thank you so much for the workaround, @SpaceshipOperations !!

For me it was the Bookmarks menu where I needed it because the containers were combined in a "open in" sub-menu after the updated. By default, there is no unlabelled section at the top of the menu, but in a fit of desperation (lol), I deleted the existing title, and it revealed icons!

Further testing revealed that this works on basically all sub-menus... if you click on the little > next to a sub-menu in Sidebery's settings, you can reveal a sub-menu label, and if you leave it blank, it will show only the icons. So you don't actually need to move the "Container..." entry into the unlabelled section at all if you only want icons, just click the > to reveal the sub-menu title option. Personally, I would move the entry to the top anyway, for ease of access.

(Note: if you decide you hate the icon after all, you just click either the v or ^ on the corresponding sub-menu to remove the empty sub-menu label.)

Thank you for everyone's hard work on this awesome extension!
