### ISSUE TITLE
Snapshot limit does not work

### ISSUE THREAD

**Issue by Elaws** [mbnuqw/sidebery#1294]
Setting snapshot limit to `1 snapshot` does not work : 

![image](https://github.com/mbnuqw/sidebery/assets/52013479/167d85a5-4ba4-4ad0-a7d1-d98af8342cb6)

![image](https://github.com/mbnuqw/sidebery/assets/52013479/264f3482-8fcd-4951-9562-545827746383)

**Comment by llc0930** [comment]
I think maybe you misunderstood.
If you go into the snapshot viewer, you'll notice that there's always only one snapshot there.
The files you see are automatically exported every time a snapshot is updated.

**Comment by Elaws** [comment]
Thank you. A limit on number of exported files would be nice though.

**Comment by llc0930** [comment]
So have you tried changing the automatically exported file name?

**Comment by Heyian** [comment]
For anyone who is stumbling on this issue just like me, are on Windows and would like to automate the cleanup of the folder, I made a daily Task with the Task Scheduler to clean files older than 15 days in the folder. Here's how I did it :

1. Open Task Scheduler and make a new task, I named mine "Delete old Sideberry exports"

2. In the New Action window, specify the following data:

    Action: Start a program
    Program/script: `ForFiles.exe`
    Add arguments (optional): `/p "C:\Users\{user}\Downloads\Sidebery" /s /d -15 /c "cmd /c del @file"`
    Even though Windows says it's optional, it is not for our case, don't skip this.
    ### Don't forget to change the location to **_YOUR_** Sideberry export folder

3. Set the Trigger:
        Go to the Triggers tab and click on the New button.
        Under the Begin task, select a schedule in the drop-down list, I chose Daily.

4. Configure Settings:
        Switch to the Settings tab.
        Enable "Allow task to be run on demand" and "Run task as soon as possible after a scheduled start is missed".
        Click OK to create your task.

And that's it, it nows cleans up the folder everyday, it's super fast and I don't expect much hiccup with this method.

Don't forget to test it before simply letting it do it's job ;)

**Comment by davidleejy** [comment]
Thanks Heyian for sharing your method for managing the number of snapshots backed-up, and for referencing this issue in  a similar one (issue #1411)  😄

Re-examining this problem two months after opening issue #1411, I suspect that this problem of Sidebery not natively providing an option to delete older snapshots isn't serious for many users primarily because snapshot files are quite small relative to the hard drive memory common in modern entry-level computers. Currently, I have between 500 to 800 tabs opened in Firefox and all of them can be saved to a single snapshot file (as .json, or .md format) sized ≤400kB.

I have not implemented any automation to clean up snapshots (e.g., with task scheduler, or chron). I've configured Sidebery to save snapshots once every three days – resulting in 10 snapshots per month. Having configured each snapshot to be saved in two file formats – md & json – and with each file occupying fewer than 400kB (thus ≤800kB for two files), my Sidebery snapshot back-ups consume at most an additional 8mB per month, or at most 96mB annually. At this rate, I think it'd all right to manually house-keep the Sidebery snapshots directory once annually or even once every three years.

I'm writing to share my thoughts because I don't wish to alarm other Sidebery users, especially those new to Sidebery, to cause them to eschew Sidebery 😆

_______

**A Related Issue: How to Automatically Back-up Sidebery Snapshots onto a Cloud**

A bit of a digression from the issue here, but I figured that people looking at backing up their snapshots might also be considering about placing their snapshots on a cloud (e.g., dropbox, microsoft onedrive, google drive), and as such, might benefit from reading about the steps I took to accomplish this which I document in detail in [discussion #1497](https://github.com/mbnuqw/sidebery/discussions/1497)

**Comment by Heyian** [comment]
I totally agree, it's more of an OCD thing than anything else... I've had snapshots taken every 15 minutes and have about 300 tabs open at the moment, my cleanup has cleared a whole whopping 13MB and this was for 3-4 months of use. Doing annual cleanup is actually a better idea to be honest 😁

**Comment by mbnuqw** [comment]
It's not possible to automatically remove old snapshot files from Sidebery (and from any other addon) side, the limit is applied only on snapshots in Sidebery's internal storage (those snapshots that appear in snapshots viewer).

So, only a third-party program/script can be used (e.g. @Heyian's suggestion).

Note: To reduce the count of exported snapshots, you can update "Path with file name" field to something like "Sidebery/snapshot-%Y.%M.%D". This way, only the latest snapshot of a day will be stored.

**Comment by davidleejy** [comment]
> It's not possible to automatically remove old snapshot files from Sidebery (and from any other addon) side, the limit is applied only on snapshots in Sidebery's internal storage (those snapshots that appear in snapshots viewer).
> 
> So, only a third-party program/script can be used (e.g. @Heyian's suggestion).
> 
> Note: To reduce the count of exported snapshots, you can update "Path with file name" field to something like "Sidebery/snapshot-%Y.%M.%D". This way, only the latest snapshot of a day will be stored.

@mbnuqw Quick question, does that mean users can automatically get no more than a month's worth of daily snapshots (roughly speaking) if users change the path with filename field to something like "Sidebery/snapshot-%D"?

**Comment by Heyian** [comment]
Yes you got it right @davidleejy, it will effectively overwrite the file that has the same day of the month.

**Comment by davidleejy** [comment]
Sweeeeeet
