### ISSUE TITLE
[Feature Request] Mirror highlighted Sidebery tabs in native tabs

### ISSUE THREAD

**Issue by ghost** [mbnuqw/sidebery#1464]
## Description

It would be _really_ nice if multi-selected / [highlighted](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab#highlighted) tabs in Sidebery were mirrored natively. I find selecting tabs from Sidebery to be a much better experience than selecting them natively. The only problem is that when I use Firefox's tab close keyboard shortcut, it only closes the active tab. I believe the [`tabs.query()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/query) API could be useful here in mirroring the highlighted state.

**Comment by kitt-cat** [comment]
What a coincidence I just arrived here for exactly the same reasons :sweat_smile: 

Turns out there is an option "Highlight native tabs..." in Sidebery settings / Tabs / Native (horizontal) tabs (thanks to comment https://github.com/mbnuqw/sidebery/issues/1441#issuecomment-1921131077). So far its working perfectly for me!

Wondering why syncing selection is not the default behavior? I tried to blame but there are no commits before https://github.com/mbnuqw/sidebery/commit/17e18af74e84dd9bd74c323f8f364c58ad902559 which doesn't offer much explanation..

**Comment by ghost** [comment]
> Turns out there is an option "Highlight native tabs..." in Sidebery settings / Tabs / Native (horizontal) tabs (thanks to comment [#1441 (comment)](https://github.com/mbnuqw/sidebery/issues/1441#issuecomment-1921131077)). So far its working perfectly for me!

Ah! How could I have missed this 🙈 Thank you.

> Wondering why syncing selection is not the default behavior? I tried to blame but there are no commits before [17e18af](https://github.com/mbnuqw/sidebery/commit/17e18af74e84dd9bd74c323f8f364c58ad902559) which doesn't offer much explanation..

I'm curious about that as well. Perhaps this issue could be repurposed to push for this. Also, now that I've enabled the native highlight feature, I'm wondering if the mirroring could go in the opposite direction (i.e., highlighting the horizontal native tabs highlights them in Sidebery).

**Comment by mbnuqw** [comment]
Fixed in 5a6f05b7daa4081e10caaf93f6523a9c99219834
