### ISSUE TITLE
Key bindings lost on update.

### ISSUE THREAD

**Issue by zelch** [mbnuqw/sidebery#1477]
## Steps to reproduce
Have active key maps.

Let Firefox update Sideberry automatically in the background.

## Expected behavior

Everything keeps working.

## Actual behavior

All of the keybindings stop working in currently open windows.

If you open a new window, that will have functional keybindings.

Likewise, if you close Firefox and restart, that will also fix things.

But rebinding in settings does _not_ work, that is, it can happily pickup the keys that you're trying to bind, but if it is the same binding they still don't work.

If it is an entirely new key sequence that has never been bound to something, it works just fine.

I'm not sure how to trigger the same update flow manually, or I would spend some time debugging it.

Looking through the code, I don't see how new bindings would be working at all if our listener (keybindings.setupListeners and keybindings.resetListeners) had gotten lost.

Hitting reset addon isn't enough to fix things, same with 'Reset Keybindings'.

Same with exporting the keybindings and reimporting them.

So without being able to reproduce this at will, I'm not sure how to debug this further.

**Comment by zelch** [comment]
I am no longer certain that this isn't a straight Firefox bug.

Debugging the extension while in the broken state shows that we _should_ be getting everything for the key bindings in question, browser.commands has them, with the correct shortcuts, and onCmd is properly registered.

But for key sequences that were bound before the extension upgrade, we just don't get called.

**Comment by visua0** [comment]
Looks like the same thing I run into: #1470
Indeed it appears to be happening during the daily update since I'm on the nightly version. Gonna switch to the stable release for the time.
Still not sure how the blank sidebars fit in. Sometimes it happens at the same time and sometimes it happens on launching firefox.

**Comment by mbnuqw** [comment]
Finally, I've managed to reproduce this Firefox bug! Thanks, @zelch and @visua0!
Bugzilla link: https://bugzilla.mozilla.org/show_bug.cgi?id=1881820

**Comment by megamorphg** [comment]
@visua0 I've been having this issue the past 2 weeks too, likely after one of the recent Firefox upgrades. Glad this isn't caused by any of the Firefox scripts I have or Sidebery. I'm currently on the latest 123... did you say you're not having the issue in a different version?

Also, it only affects keybindings for Sidebery. Are we sure it isn't something Sidebery related? I can use ATD shortcut to discard current tab or open history sideview with Ctrl + H.

**Comment by mbnuqw** [comment]
The issue only occurs if the addon runs command listener in the sidebarAction, so if the Bugzilla ticket doesn't attract attention, I'll just move the logic of keybindings to background. That was planned anyway (partially).
