### ISSUE TITLE
"Do not expand sidebar on hover" setting.

### ISSUE THREAD

**Issue by lasersPew** [mbnuqw/sidebery#1525]

**Comment by mbnuqw** [comment]
There is no setting to hide/show sidebar, since it's not possible for addon to do that on mouse-enter/leave. Only [userChrome.css hacks](https://www.reddit.com/r/FirefoxCSS/search?q=auto+hide+sidebar&restrict_sr=on). Also, track [this bugzilla ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1408077)
