### ISSUE TITLE
Don't require a modifier for keybindings

### ISSUE THREAD

**Issue by rieje** [mbnuqw/sidebery#1538]
### Description

Feature request: don't require a modifier for keybindings. I use [Vimium C](https://github.com/gdh1995/vimium-c) and it allows for one-key bindings. It has some free single-character keys like `a` and `s` that I want to bind on Sidebery.

**Comment by mbnuqw** [comment]
There are two ways of handling keybindings:
- Vimium C injects its scripts into pages, where it handles raw keyboard events. This approach requires "Access your data for all websites" permission and doesn't work in all pages (don't work in internal Firefox pages, reader view, view-source, and PDF viewer pages).
- Sidebery uses [commands API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/commands) which has [limitations, including required modifier](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#syntax), but its work doesn't depend on the current active tab.

Wontfix - because it will bring inconsistency in behavior depending on what page is active, and I strongly against of making the "Access your data for all websites" permission required.
