### ISSUE TITLE
"Undo close tab" missing from context menu

### ISSUE THREAD

**Issue by mbaz** [mbnuqw/sidebery#16]
The context menu has some very useful options, but it's missing "undo close tab", which I find essential to recover tabs closed by accident.

Sideberry v2.2.1, Firefox 66.0, Archlinux.

**Comment by mbnuqw** [comment]
Yep, I plan to add Undo action (for bookmarks and tabs). And I want to add ability to choose removed item[s] to restore. But I don't know yet how to implement it in UI. Since it's a general action I cannot just add it to context menu.
Options are:
-- add it in dashboard menu
-- show button at the bottom after some tab/bookmark was closed

And I don't really like both of these options...
Anyway, I need to test different variants.

**Comment by mbaz** [comment]
One idea would be to add a context menu option to just restore the most recently closed tab. That is what Vertical Tabs Reloaded and Tree Style Tabs do. For more fine-grained tab restoring, Firefox's "history" menu already provides a list of recently closed tabs, so you may not need to re-implement that.

Restoring deleted bookmarks is an intriguing idea. I've never needed it, but I do backup my bookmarks every once in a while...

**Comment by mbnuqw** [comment]
You right, I somehow forget about "Library/History" menu :smile: 

What if I add customizable strip with "easy access" actions?
Something like that (this is just random icons):
![screenshot-2019 03 26-23 12 50_1](https://user-images.githubusercontent.com/6276694/55022771-249c2f80-501d-11e9-8a5b-57ca58c0a775.png)

So you can assign Undo and any action you want.

...and even more, I can allow user to completely customize context menu.
hm... I need some time to test it.

**Comment by mbaz** [comment]
That'd be awesome.

**Comment by mbaz** [comment]
Seems to work -- thanks!

**Comment by Jipok** [comment]
On my system it looks like this:
![image](https://user-images.githubusercontent.com/25588359/58761401-8dc78400-8533-11e9-8ac5-df6dac35e3ec.png)
What in my opinion is unfortunate. I thought this was the "Go back one page" button and only a search on the github questions made it clear where the "Undo close tab" is located.

**Comment by mbnuqw** [comment]
Hmm, you are right, icon can be counterintuitive and unfortunately there are only two ways for new user to know what it means - read tooltip on mouse hover or just click on it. If you have any suggestions of how this icon should look like, feel free to open new issue.

**Comment by Jipok** [comment]
Most common icons:
![image](https://user-images.githubusercontent.com/25588359/58828887-fb5bd900-8635-11e9-9ac4-36ea286defa2.png)
From [flaticon](https://www.flaticon.com/search?word=undo)
[Can also be found here.](https://duckduckgo.com/?q=undo+icon&t=ffab&iar=images&iax=images&ia=images)

![image](https://user-images.githubusercontent.com/25588359/58828783-b89a0100-8635-11e9-9ca6-cc760d46e7d0.png)
From [Nerd fonts](https://nerdfonts.com/).

I think the third option (the most right) looks better.

**Comment by Jipok** [comment]
In TST for this action you need to install one of several external add-ons. Therefore i think the “Undo Close Tab” feature is worth mentioning in the features list or in the tips and tricks.

**Comment by TheOverpassArsonist** [comment]
I also absent mindedly thought it was a back button but discovered what it was by looking up how to undo a tab close was when I found this post. (though tbf I'd consider this user-error since, why tf would that be a back button? And, eitherway, I definitely should've at least hovered over it to read the tooltip)

With that said however, I do think the icon could be changed to improve clarity of function. (user error or not) I am by no means a graphical artist or UI designer, but I think repurposing the existing 'closed tabs'/'trash' icon would be a good idea here, since conceptually they share a near-identical purpose. 
![Image](https://github.com/user-attachments/assets/c9cfbf0b-c1b4-42db-9b7a-c8e8d78d71e6)

In normal use it would look something like this

![Image](https://github.com/user-attachments/assets/780f4f9f-f54e-440f-b5b6-fb52336c3cd8)

and then if the user clicks on that it will pull up the existing closed-tabs window that this icon is already currently associated with (note : the UI pedant in me finds it a bit annoying that hitting the button that could be anywhere in the panel opens up a new change on the bottom of the panel, but tbh I don't think there's any way around that)

but then if the user has closed a tab or tab-tree in the past 10-30 seconds it will look like this

![Image](https://github.com/user-attachments/assets/b313521b-22e1-48a7-abec-d5d6f8419c68)

and clicking on it would restore the last closed item. 

This would make it incredibly clear what the button does and make it also have a use outside of _just_ restoring the last closed tab. (since I'm not sure I have _ever_ reopened my last closed tab when that tab was closed >30s ago.) 

Also, I'm not sure if it's possible but I'd personally appreciate it if a similar behaviour existed for ctrl-z, so if a tab (or tab tree) was closed in the past 5-10 seconds pressing ctrl-z would automatically restore it. (though I recognize that this is a new feature that should probably be it's own discussion)
