### ISSUE TITLE
Different tab close behavior if current tab was opened as a foreground tab instead of a background tab

### ISSUE THREAD

**Issue by nearcatch** [mbnuqw/sidebery#164]
I have tab focus on closing set to go to the previous tab in the tree. This is because I usually open tabs in the background. Can an option be added to focus to the previously selected tab if the current tab was opened/selected as a foreground tab?

**Comment by mbnuqw** [comment]
Sorry, it will be quite difficult to add such option.

**Comment by aletaziar** [comment]
Ok. The main reason I was asking is focusing on the next tab in tree after closing doesn't really behave properly when you open a foreground tab from a pinned tab. Instead of going back to the pinned tab it goes to the end of the tree, or to an unrelated pinned tab.

**Comment by mbnuqw** [comment]
Hm... yeah, this is not very usable. Ok, I'll think about what I can to do here.

Maybe adding a rule for tabs that was open from pinned tab will work? Something like "If parent tab is pinned return focus to it after closing current tab". But this will apply for both foreground and background tabs.

**Comment by aletaziar** [comment]
Maybe an option to automatically create a special automatic group of tabs for tabs opened from a pinned tab. Then tree behavior would act normally, and you code it so when the last tab in the tab group is closed focus goes back to the pinned tab.

1. pinned tabs: A B C
2. Open background Tabs 1 and 2 and foreground Tab 3 from Pin A
3. They automatically go to a tab group called "Tabs from Pin A". Focus is on Tab 3.
4. Close Tab 3 and focus goes to Tab 2. Close Tab 2, focus goes to Tab 1.
5. Close Tab 1, and no more tabs are in group "Tabs from Pin A". Special coding says that when "Tabs from Pin A" is closed, focus back to Pin A instead of the normal focus behavior.

**Comment by mbnuqw** [comment]
I'm experimenting with it now and found out that grouping tabs that way is even more complicated to implement than the initial request :D.

Anyway:

![Peek 2020-03-15 20-47](https://user-images.githubusercontent.com/6276694/76704943-38451800-66fe-11ea-8fe7-c3a838988e95.gif)

Is this a desired behavior?

**Comment by aletaziar** [comment]
Yep, that seems like exactly what I'm looking for. Will those tabs always close back to the pinned tab? What happens if you select another tab and do some other stuff and then come back to the child later?

**Comment by mbnuqw** [comment]
`Will those tabs always close back to the pinned tab?` - If there is a neighbor tab that was opened from the same pinned tab it will be activated, otherwise pinned tab will activated instead.

`What happens if you select another tab and do some other stuff and then come back to the child later?` - as long as sidebar is open the new behavior will persist.

The algorithm is essentially works like this:
```
if active tab was open from pinned tab:
    if next or previous (depending on settings) tab was open from the same pinned tab:
        activate that tab
    otherwise:
        activate pinned parent
```

Another example:

![Peek 2020-03-16 11-47](https://user-images.githubusercontent.com/6276694/76730372-ea232980-677c-11ea-8e7d-57ce9e45f64b.gif)

Also note that this will work only for the "next tab" and "prev tab" options in the settings.

**Comment by aletaziar** [comment]
Works for me, thanks. What happens if you drag the tab opened from the pin into a different tree? Would it still go back to the pin instead of to the next tab in that other tree?

This isn't a big deal, I will just close and reopen the sidebar to reset the behavior if that's the case.

**Comment by mbnuqw** [comment]
`What happens if you drag the tab opened from the pin into a different tree?` - this is a good question. Right now relation between the child tab and the pinned one persists as long as the tab is open, but I'm still not sure about this behavior. Maybe, it would be better to reset this after tab was moved or after another event (e.g. after activation of the "outside" tab that is not linked to pinned tab and its children).

I'm open to any suggestions regarding this feature :)

**Comment by aletaziar** [comment]
<ol><li>I think the most intuitive way is to have these child tabs behave like a tree where the pinned tab is the parent item. So dragging an item to another tree should break the relationship to the pinned tab, since it's no longer in the pin's fake tree.</li>
<li>This bring's up a different question, if I understand the implementation you have right now. How are you grouping the tabs and signifying they're grouped? Consider this example, with "previous tab" selected as the preferred closing behavior, and "panel end" selected as the location for new tabs from pin tabs.</br>
   <ol type="1"><li>Pinned tabs: A and B.</li>
   <li>Open tabs 1 and 2 from A. Open tabs 3 and 4 from B. Open tabs 5 and 6 from A.</li>
   <li>Focus tab 6. Close that, it will jump to 5. Close that, and it will jump to **tab 2**, skipping over tabs 3 and 4.</li></ol>
From your examples it looks as though there is no indication that pin's children are related in any way, so to a user it will be perhaps surprising that tabs 3 and 4 in the example are skipped. Tree Style Tabs avoids this with an option to group pinned children under a header, which is why I suggested it above.</li>
<li>Final question: What happens when you unpin a tab that has these fake children? I think the pinned tab should become the parent of all the children it has opened, but maybe that's complicated to code. Intuitively it makes sense to me though.</li></ol>

**Comment by mbnuqw** [comment]
Thanks for the input! Yep, looks like, the Tree Style Tabs way (with group page) is more practical and intuitive. I'll try to implement something like that.

And about third point - this is possible and actually not very difficult to code.

**Comment by aletaziar** [comment]
Great! The only thing I'll add that I thought of is the *reverse* should also be true: If you pin the parent of a tree (call it Pin N), then its old children should be put under a group page saying "tabs from Pin N". That way the relationship between tree parents and children is preserved. Right now if you pin the parent of a tree and then unpin it, it gets orphaned and the former tree no longer exists.

**Comment by mbnuqw** [comment]
Initial support of auto-grouping children of the pinned tab added in v4.7.0.

**Comment by aletaziar** [comment]
Been testing this and so far this is working great. One suggestion is that after closing a pinned tab's child, the "undo close tab" action should open up the child tab that was closed. Right now "undo close tab" opens up the fake group page for the pinned tab.

**Comment by aletaziar** [comment]
A few more days of testing and I have run into an issue. Tabs opened from a pinned tab with the url "https://news.google.com/topstories?hl=en-US&gl=US&ceid=US:en" do not focus back to the pin. Instead they focus to the end of the tree.

**Comment by mbnuqw** [comment]
@aletaziar, can confirm this. Will be fixed in the next version.

**Comment by nearcatch** [comment]
> @aletaziar, can confirm this. Will be fixed in the next version.

Thanks, just tested with latest version and it works now.

Separate usability issue. When a tab is opened from a pin, is there a way to exclude the group tab from the ctrl-tab switching behavior? Sometimes I want to switch back to the pin quickly but instead I end up at the group tab.

**Comment by mbnuqw** [comment]
`is there a way to exclude the group tab from the ctrl-tab switching behavior`
No, unfortunately, there is no way to do that. I personally use the "ctrl+number" shortcut for switching to the pinned tabs and Sidebery's keybinding to switch to the previous active tab. Hope this help.

`just tested with latest version and it works now.`
Good! I'm closing this issue, so if you will have any problems or suggestion feel free to open new issue.
