### ISSUE TITLE
[BUG] Cannot drag-and-drop outside of sidebar to open new window (FF version >= v129.0b2)

### ISSUE THREAD

**Issue by the-nelsonator** [mbnuqw/sidebery#1714]
### Steps to reproduce

- Open Firefox Dev Edition 129.0b2, or Firefox Nightly v130.0a1 (2024-07-12) in a new profile
- Install Sidebery v5.2.0
- Try to drag a tab outside of sidebar

### Actual behavior

Does nothing

![sideberydraganddrop](https://github.com/user-attachments/assets/d007a1ad-2918-4040-a356-6f3c972c03c3)

### Expected behavior

Opens a new window with the tab

### System

Windows 11

### Firefox version

 Open Firefox Dev Edition 129.0b2, or Firefox Nightly v130.0a1 (2024-07-12)

### Sidebery version

v5.2.0

### Logs

No logs at all in console.

### Notes: 
- Works as expected on vanilla Firefox 128.0 
- Swapping the "Action on drag-and-drop to the outside of sidebar" setting to "Pass dragged data to the target" shows that it's still registering the drag and drop, i.e. if I drag a tab in here: moz-extension://b6832724-3975-40ee-953f-845199cf5989/page.setup/setup.html#settings_dnd

**Comment by the-nelsonator** [comment]
@rebelonion I noticed you used Dev Edition on 06/26 to demo your PR related to drag and drop: https://github.com/mbnuqw/sidebery/pull/1698. 

On my machine drag and drop is not working as of Dev Edition 129.0b2 (released 7/10). Is the same true for you? Helps narrow down timeframe or if this is just due to something in my environment

**Comment by sebibasti0815** [comment]
Problem exists in 129.0b3, too. "Workaround" using ff extension [tabdetach](https://addons.mozilla.org/en-GB/firefox/addon/tabdetach/) and using keyboard shortcuts.

**Comment by the-nelsonator** [comment]
Right-click tab -> Reopen in -> New window is also a less convenient workaround

**Comment by sebibasti0815** [comment]
"Move to", but, yeah 👌😂

**Comment by beracira** [comment]
Regarding the note: I can reproduce the issue on 
```
Version 	128.0
Build ID 	20240704121409
```
The ability to rearrange tabs with the sidebar is also affected.

**Comment by StudioNirin** [comment]
For me the issue (on 128) is that when I try and open a tab in a new window by dragging (or using the 'open in new window' right click menu option) the window opens fine... but sidebery is no longer open in that window. Not sure if that's related or a different bug entirely.

**Comment by beracira** [comment]
I found a fix (well, as least for my issue): 
Changing `dom.events.dataTransfer.imageAsFile.enabled` to `true` in `about:config` seems to fix the issue.

It looks like a regression: [bugzilla link](https://bugzilla.mozilla.org/show_bug.cgi?id=1437126).

**Comment by StudioNirin** [comment]
Ah unfortunately that doesn't fix my issue. Even more unfortunately i haven't seen the dev respond to any bug reports for a few months.

**Comment by sebibasti0815** [comment]
> I found a fix (well, as least for my issue): Changing `dom.events.dataTransfer.imageAsFile.enabled` to `true` in `about:config` seems to fix the issue.
> 
> It looks like a regression: [bugzilla link](https://bugzilla.mozilla.org/show_bug.cgi?id=1437126).

That doesn't fix the problem here. It's a different problem, dragging images - our problem in this case is dragging tabs.

**Comment by the-nelsonator** [comment]
Yeah, tried `dom.events.dataTransfer.imageAsFile.enabled` to `true` on v129.0b6 and can confirm did not fix the drag'n'drop to open in new window

**Comment by Bobo1239** [comment]
I've [bisected](https://mozilla.github.io/mozregression/documentation/automatic-bisection.html) the issue to [this Firefox change](https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=9ac7f1f672d585d3a66062be012715bfafbb1e4d&tochange=01bfc9faa69043308206f123a4f171b426aa2758) which makes sense since it touches the drag'n drop subsystem. The effect is that in [this Sidebery line](https://github.com/mbnuqw/sidebery/blob/aa476a47f3663230ee5722d1a3cebffe4faf3192/src/services/drag-and-drop.actions.ts#L1206) `e.dataTransfer` is now `null` instead of a `DataTransfer` object. (which alters our control flow) According to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/DragEvent/dataTransfer) this should never happen when the event is dispatched by the browser which is the case here so I'd say this is a Firefox bug.

Unfortunately I don't have time to dive more deeply into the Firefox change so somebody else will have to do that... (I've also open a bugzilla issue for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1911486)

**Comment by the-nelsonator** [comment]
@Bobo1239 Thank for identifying the issue (noting down that bisection tool, very cool) and reporting on Bugzilla. Looks like David Parks/handyman already got a fix in - drag and drop to open in other window works as expected in v131! (Only on Nightly for now)

Looks like, as expected since you opened a separate Bugzilla, this did not fix the [issue with tabs "cloning" in the other window instead of moving. ](https://github.com/mbnuqw/sidebery/issues/1723)

**Comment by sebibasti0815** [comment]
> drag and drop to open in other window works as expected in v131! (Only on Nightly for now)

It works in 130.0b4, too. But the other issue (tabs cloning instead of moving) is there, too.
