### ISSUE TITLE
Add History panel

### ISSUE THREAD

**Issue by zilexa** [mbnuqw/sidebery#187]
## By default Sidebery shows a Bookmarks and a Default panel. 
Is it possible to add a panel here that shows the browser history?

Or even multiple panels:
- History
- Downloads
- Synced Tabs

**Comment by mbnuqw** [comment]
Yeah, I've already thought about different types of panels, but so far it's just been ideas with low priority level. About suggested panels - History and Download panels can be implemented (with optional permissions), but the "Synced Tabs" panel, unfortunately, cannot.

If you have any ideas (UI, features) regarding the History panel feel free to write them.

**Comment by aletaziar** [comment]
Ideas for history panel:
<ul><li>highlighting currently open tabs, like bookmarks does</li></ul>
Ideas for bookmarks, history, and download panels:
<ul><li>search/filter abilities</li>
<ul><li>by title/name or URL</li>
<li>for bookmarks, filter by tag</li>
<li>for bookmarks, filter by bookmarked date or accessed date</li>
<li>for history, filter by accessed date</li>
<li>for downloads, filter by download date</li></ul></ul>

**Comment by Keagel** [comment]
Adding onto it: a panel for Bitwarden - the app allows you to pop-out and it opens a window with an URL like this:

moz-extension://{EXTENSION_ID}/popup/index.html#/tabs/vault

which can be opened into any tab. I'm aware Bitwarden has a sidebar already (Alt + Shift + Y), though only one sidebar can be opened at a time, so you have to reopen Sidebery after using it.
Rather than having you do any requested extension one by one like this - you could give us the ability to create a custom panel in the settings: we give it the extension URL that's to be opened and that's it. We could essentially get a better overflow menu using this.

**Comment by ovnis82** [comment]
Any news about that?

**Comment by jathek** [comment]
> Any news about that?

There's a history panel in the v5 beta.

**Comment by ovnis82** [comment]
Great!

**Comment by emvaized** [comment]
If Downloads panel will be implemented, I'm curious if it could support drag-n-drop? So that you could quickly drag any file to the input field on page, for example.

**Comment by mbnuqw** [comment]
Closing as implemented (History panel)
