### ISSUE TITLE
Move tab's close button to the left side

### ISSUE THREAD

**Issue by emvaized** [mbnuqw/sidebery#293]
## Description
Ideally with this setting enabled, it should appear on the place of favicon on mouse hover. But in this case it will interfere with group arrow indicator, so maybe this indicator should be placed on the right when this option is enabled, or isn't shown at all.

Maybe somebody will share some custom css on how to achieve this?

**Comment by emvaized** [comment]
For those wondering -- here's custom css, which helped me to achieve this.
You should paste it to the right sidepanel in styles editor, in Sidebery settings.

```
/* Close button on left, with animation */

.Tab .lvl-wrapper .close {
  left: 0px;
}

.Tab:hover {
  width: 120%;
}

.Tab .lvl-wrapper .close svg {
  opacity: 0.0;
  transition: all .15s ease-in-out;
  transform-origin: center;
}

.Tab .lvl-wrapper:hover .close svg {
  background-color: white;
  border-radius: 4px; 
  opacity: 1.0;
  transition:  all .15s ease-in-out;
  transform-origin: center;

}

.Tab .lvl-wrapper .close:hover svg{
  background-color: red;
  transition:  opacity .125s ease-in-out;
  fill: white;
}
```

Here's the result:
![screen record](https://user-images.githubusercontent.com/37851576/90287731-1e605a80-de81-11ea-8c28-5a7bfaea8572.gif)

**Comment by emvaized** [comment]
Here, with a few design modifications:

```
.Tab .lvl-wrapper .close {
  left: -1.25px;
}

.Tab:hover {
  width: 120%;
}

.Tab .lvl-wrapper .close svg {
  opacity: 0.0;
  transition: all .15s ease-in-out;
  transform-origin: center;
}

.Tab .lvl-wrapper:hover .close svg {
/* Adjust this to edit non-hovered background 
and opacity */
  background-color: white;
  opacity: .9;
  border-radius: 66px; 
  transition:  all .15s ease-in-out;
  transform-origin: center;

}

.Tab .lvl-wrapper .close:hover svg{
  /* Hovered color */
  background-color: red;
  transition:  opacity .125s ease-in-out;
  fill: white;
}
```
![screen record](https://user-images.githubusercontent.com/37851576/90288446-90856f00-de82-11ea-9fb0-6d8b8df545f7.gif)

**Comment by emvaized** [comment]
Small modification, to handle arrows for collapsed trees:

```
.Tab .lvl-wrapper .close {
  left: -1.25px;
}

.Tab[data-parent="true"][data-folded="true"] .lvl-wrapper .close {
  left: 21px;
}

.Tab:hover {
  width: 120%;
}

.Tab .lvl-wrapper .close svg {
  opacity: 0.0;
  transition: all .15s ease-in-out;
  transform-origin: center;
}

.Tab .lvl-wrapper:hover .close svg {
/* Adjust this to edit non-hovered background 
and opacity */
  background-color: white;
  opacity: .9;
  border-radius: 66px; 
  transition:  all .15s ease-in-out;
  transform-origin: center;

}

.Tab .lvl-wrapper .close:hover svg{
  /* Hovered color */
  background-color: red;
  transition:  opacity .125s ease-in-out;
  fill: white;
}
```

Close button is shifted by 20 pixels to the right, in order to not cover arrow button.
<img width="154" alt="Снимок экрана 2020-08-15 в 02 27 00" src="https://user-images.githubusercontent.com/37851576/90299592-48287a00-de9f-11ea-9ea4-474ea9e6940b.png">

**Comment by AndydeCleyre** [comment]
It would still be nice to have this available in the settings, without writing custom CSS.

**Comment by yarub123** [comment]
@emvaized Thank you for sharing this man! for some reason everything works awesome except for the arrow button isalso still under the x button :/

**Comment by emvaized** [comment]
@yarub123 
Try to remove `[data-folded="true"]` from the line 5, maybe it would help

**Comment by yarub123** [comment]
@emviazed lol i literally went back to history and came back to reply and
say i got it. you are too fast my guy haha. I added another line
.Tab[data-parent="true"] .lvl-wrapper .close { left: 19px}
you can mess with the px as you want of course, 19 is cutting it pretty
close but still enough distance between arrow and close for it to work

**Comment by emvaized** [comment]
Yeah, you basically did what I suggested but added this as a new rule, thus overriding previous rule :)

**Comment by yarub123** [comment]
ahaha yeah im stupid, tbh with you i have never done any form of coding or
anything but been playing around with all this css lately this shit is fun
dude. Thanks though for the prompt help brothaman

**Comment by yarub123** [comment]
right now im just trippin on the settings button. i want to move it next to
the "+" new tab button. instead of the default all the way on top right.
these are the two things i found in style editor that may be the ones that
need changing but can't figure it out. idk if you had done this before or
anything thats why im asking.

.Sidebar .settings-btn {
 position:relative;
 display:flex;
 width:var(--nav-btn-width);
 height:var(--nav-btn-height);
 justify-content:center;
 align-items:center;
 flex-shrink:0
}
.Sidebar .settings-btn > svg {
 position:absolute;
 width:16px;
 height:16px;
 fill:var(--nav-btn-fg);
 opacity:.5;
 transition:opacity var(--d-fast)
}

**Comment by siddhpant** [comment]
Maybe a consistent way could be to move the collapse button to the right, or maybe collapse on click to the tab itself...

**Comment by yarub123** [comment]
Hmm not sure what you mean Siddh, can you elaborate on that? Also this was
a year ago so I'm not remembering it too much, but I did read the thread
and got familiar with it. Thank you.

**Comment by siddhpant** [comment]
On Sat, Dec 3 2022 11:29:11 +0530, yarub123 wrote:
> Hmm not sure what you mean Siddh, can you elaborate on that?

I mean the implementation (many thanks to emvaized) here is to move the cross button from the icon because the tree collapse button is there.

![image](https://user-images.githubusercontent.com/25429745/205434256-0833620a-c633-4739-b959-a2bac16a151a.png)

What I meant was the collapse button may be moved to the right end, and/or tab may be collapsed on click, so the cross button may be used on the icon like other tabs.

> Also this was a year ago so I'm not remembering it too
> much, but I did read the thread and got familiar with it.

Really sorry for necroposting...

**Comment by yarub123** [comment]
@siddhpant oh nah man haha don't be sorry. I only mentioned the year ago comment because I forgot exactly what was the issue. But now upon rereading your message. Yes I think that is a brilliant idea to either being able to move the collapse button OR even better would be to have an option in the settings that allows it to collapse on click (or maybe even long left click?) Either way nice idea. 

Sorry about that, I thought you wanted help with the X button. I hope you figured it out!

(for the record I now just use the default X on the right, but as of recently not using Sidebery for now, using something else, but yeah) 12/19/22, 3:14 AM

**Comment by barbax7** [comment]
Hello there
Sorry, but i can't implement this style

I copied [this code](https://github.com/mbnuqw/sidebery/issues/293#issuecomment-674310534) in my right side of sidebery style editor, but nothign happened (i changed from 120% to 100% because my panel is smaller, so close button would be on the right outside of the panel).

I don't know if the issue is in some settings I copied by a youtuber 
https://gist.github.com/morrolinux/87aa37396432ea5d14a9220bc4892100
