### ISSUE TITLE
Move unmatched children tabs into another panel

### ISSUE THREAD

**Issue by laralex** [mbnuqw/sidebery#298]
I have an organized set of panels, say
* `only search websites` all tabs matching `google.com`, `stackoverflow.com` go here 
* `only work websites` all tabs matching `upwork.com` go here
* `only email websites` 
* and so on...

The fact is, I don't want to create tabs other than matching in these panels, but at the moment when I open new children tabs in `only search websites` after following links from Google these new tabs clutter the panel.

I would like to have a feature to move all the tabs not matching this panel list of URLs into another panel (say `default`). UI wise I see this option as a part of a panel settings

**Comment by mbnuqw** [comment]
Implemented in the latest version.

**Comment by Saeverix** [comment]
@mbnuqw thanks for adding this feature. However it doesn't seem to work as intended, when using it in combination with the `Move unmatched (excluded) tabs to panel` feature.

For example: I have a separate tab panel for Bitbucket, which matches all URLs using the auto generated regex `/^https?://([0-9A-Za-z-]{1,63}\.)*bitbucket\.org/`.

This all seems to work fine when opening a Bitbucket URL in the "general" Tabs panel, Sideberry then moves the tab to the dedicated Bitbucket tab.
But when I click a Bitbucket link (open in new tab) from a page within the dedicated Bitbucket panel, Sideberry then decides to move the new page to the "general" Tabs panel.

The regex is valid because when I open that same URL in a new tab on the "general" Tabs panel, Sideberry moves it to the dedicated Bitbucket panel as expected.

**Comment by mbnuqw** [comment]
@Saeverix, could it be some redirecting? Also, check the "If tab at the top level of tree" option in the rule config (Sidebery settings > Navigation bar > Panel > Manage rules > Click on the rule to see its configuration)

**Comment by Saeverix** [comment]
@mbnuqw it's not a redirection issue, I checked in the Network tab (with persist logs option). But after unchecking the "If tab at the top level of tree" option you mentioned it works.
I did not realize that option (which is on by default) could cause this issue.

Thanks for the quick reply. And now knowing what that option does, everything is working as expected.
