### ISSUE TITLE
Drag and dropping text/link on empty panel space opens an empty tab instead of a search/the page

### ISSUE THREAD

**Issue by Vermoot** [mbnuqw/sidebery#428]
When I drag and drop a link into the sidebar, below opened tabs, I'd expect it to open a new tab with the page from the link. Same with just some plain text, I'd expect a search with the text. Instead I just get a new empty tab.

Is that expected behaviour? Do I need to enable something?

I'm also using Tridactyl, so that might be important.

**Comment by mbnuqw** [comment]
Available in the latest version.

**Comment by TheOverpassArsonist** [comment]
> Available in the latest version.

Is this behind a setting or something? It's not working as I'd expect and I don't know if it's a bug or if I'm just misremembering/misunderstanding how this worked. (I remember using it a while ago when I was trying out Sideberry, but when I tried doing it again recently it didn't work as I thought it should've)

I made a discussion on it (#2253) because I wasn't sure whether it was a bug or if I was just misremembering things but for me when I try to drag and drop a URL list it always just concatenates the URLs together and tries to search it, even if I try with only one URL.

edit : quick example image, you can probably guess what URLs I dragged in

<img width="1070" height="367" alt="Image" src="https://github.com/user-attachments/assets/d90d9123-aed0-4094-86d2-46b8ea8a7fe9" />
