### ISSUE TITLE
Security Tweaks Suggestions

### ISSUE THREAD

**Issue by ashtonx** [mbnuqw/sidebery#44]
1. Make proxy optional, As paranoid user I can see how that can be quite a scare if you don't need it. I understand it's useful feature but many people won't need to use it.

2.If possible Make it so groups don't require access to all urls. I'd prolly love to create groups to sort my url trees (which is my original purpose of checking this extension and looks great) That said i get paranoid realizing extension has permission to access and modify all my pages.. If you can't do without it.. maybe a way with access to only certain websites ?

**Comment by mbnuqw** [comment]
1. Absolutely agree with you about scary permissions, but unfortunately "proxy" permission cannot be set as optional due to WebExtension manifest format. So there is nothing I can do.

2. :thinking:  Theoretically it's possible to allow user to choose what urls can be accessed. Though "Hosts" permission is used in different places in this addon (e.g. clearing cookies / proxy / include-exclude rules). So user wouldn't be able for example choose all sites for clearing cookies and just some of them for proxy... Also, this will require some extra changes in logic of handling permissions. So currently only "all or nothing" option available. But this is great idea generally, maybe later I'll take more precise look into this.

And again, I understand you. Personally, I dig into the source code before installing any addon. And in Sidebery I'm trying to keep permissions optional when possible.

**Comment by ashtonx** [comment]
1. I understand, guess it's a no go, I can see how many people could find that feature useful after all.
Personally it's not really a killer for me i can always lookup if there's some way to block it on browser side, might actually be very good setting to turn on for the future ;D

2. In this regard that's actually nice idea when i think about it but sounds like a lot of work. What I actually meant was something simpler.
By grouping I mean the labeling function Itself, expandable named tree that doesnt contain any specific page.

It'd be great If one could sort their trees by topic, If url access is needed to create this group I feel it could be moz-extension://extension-id/*

Not really an extension programmer so I might obviously be wrong ^^;

screen of the feature I meant. https://i.imgur.com/vlK36Gw.png

**Comment by mbnuqw** [comment]
1. Oh, wait. I guess, I misread you... Proxy is disabled for all containers by default. To use it you actually need to accept "Websites data" and only after that you can configure proxy for containers.
In fact, proxy will not work without "Websites data" permission even with "Proxy" permission. This might sounds a bit confusing, yeah...))

2. Hmm, I thought that this feature not requires this permission :smile:. Ok, I'll see why I add it and remove if possible.

**Comment by mbnuqw** [comment]
Yep, I'll remove "Websites data" permission for grouping in next release.

**Comment by ashtonx** [comment]
Thanks :) This is last thing I needed for good tab management (and not using more than 1 window) :)

**Comment by mbnuqw** [comment]
Fixed in the latest version.
