### ISSUE TITLE
make sideberry use local css 

### ISSUE THREAD

**Issue by Iss-in** [mbnuqw/sidebery#449]
## Description
Currently all the css variables has to defied exclusively in sideberry css only, It will be awesome if it is able to import local system css variables. 

simpler way will be to sync it with [pywalfox](https://github.com/Frewacom/Pywalfox), its a daemon which allows its corresponding extension to pick and change user defined colors from pywal

It will be much easier to go with the pywalfox, as you can define it the way you want and the daemon package already exist. 

@mbnuqw thoughts on this ?

**Comment by mbnuqw** [comment]
Closing this, since from v5 sidebery can use colors from Firefox theme.

**Comment by isshin1** [comment]
@mbnuqw  sorry for the ping, but can you please explain how it work. 

I have a color defined in my userchrome.css

```
:root{
	--custom_color : #1997c6;
}
```

but i cant use in it in sideberry css directly

```
--bg-primary: var(--custom_color) !important;
```

**Comment by mbnuqw** [comment]
@Iss-in, as far as I know, it wont work because sidebery's styles are isolated from the browser, so it's impossible to use the vars defined in userChrome.css (or I just don't know the way). It's also not possible to make sidebery automatically read your userChrome.css (or any other file) on startup to workaround this. Sidebery uses the [standard theme API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme), so you need to use some middleware addon that will use this API to change Firefox colors, which then will be used by Sidebery.
