### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by gasman1844** [mbnuqw/sidebery#5]
Some suggestions for the bookmarks panel.
- Currently when you mouseover a bookmark, there is a very subtle highlight, the bookmark appears slightly darker. It would look better if the highlight was more obvious.
- When you middle-click on a bookmark, it opens it in a new tab (as expected), but also the mouse scroll icon appears. Would probably be better if the mouse scroll icon didn't appear.
- Would be great if you could drag URL addresses from the address bar to the bookmarks panel to store a bookmark, I don't know if this is possible.
- Thanks again for your work on this extension. I think if its page on mozilla addons site was clearer that sidebery provides an alternative sidebar bookmarks panel that replaces missing features that have disappeared from firefox over the years, there might be a lot of interest.

**Comment by mbnuqw** [comment]
Thanks for the issue
- More contrast bookmarks highlighting on hover - yes, this will be fixed in next release (currently I'm working on some style improvements). btw, in next version you can change colors for most elements.
- Ah, forgot about auto-scrolling on middle click, thanks for reporting this (I just don't use it myself)
- Yes, this possible and even planned, just little bit later...
- Fair point, documentation isn't by strong side ;)

**Comment by mbnuqw** [comment]
Fixed styles and auto-scrolling in 1.9.0, so I close this for now

**Comment by Faberman** [comment]
@mbnuqw, I've decided not to open a new issue, because it's not really an issue, it's just another suggestion. Could you add a styling option to change Tab color on mouse hover and maybe on mouse click?

P. S. Thank you for your extension! I've been using Tab Center Redux for a long time, but your extension is much better.

**Comment by mbnuqw** [comment]
Thanks, yes, I think to add more custom styles for next releases (more colors, fonts, element sizes). And I will add ability to load custom css after stabilization of internal structure.

**Comment by Faberman** [comment]
@mbnuqw, thanks. And i've just noticed that Sideberry doesn't support drag and drop tabs to bookmarks bar or folders. It's an essential feature at least for me. I have never used a button for adding new bookmarks in my whole life. :)

**Comment by mbnuqw** [comment]
Yes, currently it's not possible, but planned. Maybe even in next release.
