### ISSUE TITLE
Bad performance with a lot of tabs on tab title change

### ISSUE THREAD

**Issue by jrmuizel** [mbnuqw/sidebery#562]
## Steps to reproduce
- Get 300 tabs.
- load a page that changes the title often

## Expected behavior
no Firefox hangs. See https://share.firefox.dev/3H0I0yJ

## Actual behavior
Hanging in the Firefox UI

**Comment by AlexCzar** [comment]
I have a lot fewer tabs (around 50). But Sideberry hangs really hard, this usually happens when I open Amazon or Office365 pages.
In system resources I see WebExtensions process using 100% of a CPU core (Ryzen 7 1700x), UI becomes unresponsive (although switching between tabs via non-sideberry shortcuts still works), websites also become unresponsive.
This issue makes Sideberry completely unusable for me, had to switch back to TST.

**Comment by mbnuqw** [comment]
Closing this as stale. Please, reopen if issue is reproduced in the latest version of Sidebery.
