### ISSUE TITLE
Opening bookmark in new tab scrolls tabs incorrectly

### ISSUE THREAD

**Issue by KloolK** [mbnuqw/sidebery#594]
When I middle-click a bookmark in the bookmark bar to open it in a new tab, the tab bar sometimes scrolls all the way to end instead of where the tab was actually opened. I recorded the attached video to demonstrate the issue. It seems to happen only when I'm currently in the first sideberry panel and the following panels contain many tabs.

https://user-images.githubusercontent.com/3864672/161214048-08d4fbb2-48a4-4213-8d84-d3339ff4db52.mp4

Please let me know if you need further details or help during testing.

Many thanks for this great extension!

**Comment by mbnuqw** [comment]
Thanks for the report. This happens because when you open the link from the outside of the page, firefox opens a new tab at the end of the tabs strip, then sidebery moves it back to the last index of the active panel (depending on your settings).

So it seems like it's a firefox bug (it should scroll back, since the moved tab is active).

This cannot be fixed from sidebery side so I'm closing this issue.
