### ISSUE TITLE
[AMO] "Download failed. Please check your connection."

### ISSUE THREAD

**Issue by opes** [mbnuqw/sidebery#6]
I noticed that Sidebery wasn't showing up/activating for me today, so I tried to remove and reinstall it. However, attempting to install any addons from [mbnuqw](https://addons.mozilla.org/en-US/firefox/user/13304480/) fails and displays the following error:

<img src="https://i.imgur.com/AQz1Jmn.png" alt="Download failed. Please check your connection">

All other addons I tried to install from various authors worked as expected. Sidebery, WebAssembly Detector, and WebSocket Detector were the only addons to fail to download/install.

Firefox Nightly 66.0a1 (2019-01-21) (64-bit)
Arch Linux 4.20.3

**Comment by mbnuqw** [comment]
Can you please try it again? I just opened addons page and got strange message like 'hey, you already logged in', so I've relogged-in and check everything and everything looks fine. (maybe its because yesterday I mistakingly login into amo...)
Also, checked installing my addons from different IPs and there are no issues as well.
So I hope this was temporary (strange) issue with amo...

**Comment by opes** [comment]
Hmm, so I still am unable to download it from Nightly. However, I installed & tried using Tor Browser (since that uses Firefox under the hood) and was able to download the extension successfully. So, going to close this for now as it might be a weird caching or otherwise local issue on my machine. Going to keep troubleshooting, though, to see if I can figure out where the issue is. Thanks for looking into it!
