### ISSUE TITLE
Open link in current panel

### ISSUE THREAD

**Issue by prizrak9** [mbnuqw/sidebery#65]
When I open some link in some app the tab opens in the default panel regardless of which panel I'm in.

**Comment by mbnuqw** [comment]
I can add option like "open new page in active panel", but, because firefox by default opens tabs in default container, tab will be reopened and page will "flash". This approach is also leading to privacy breach because first request will be sent with cookies from default container. Guess, I'll need to write some warning about that...

**Comment by prizrak9** [comment]
Can you make such an ability for when working with multiple "default" panels?

**Comment by mbnuqw** [comment]
Finally, in v4.1.2 external links will open in the current panel (if option `Place new tab (for the other cases) is selected`).
