### ISSUE TITLE
Add a keybingding to unload a tab

### ISSUE THREAD

**Issue by carlosdoub** [mbnuqw/sidebery#674]
## Description
Can you add an option to add a keybinding to Unload a tab? Currently, there is a button in the context menu to unload tabs which is very useful to manually free resources. It would be great if I could do that by keyboard navigation.

Thank you for providing the addon.

**Comment by harl** [comment]
Auto Tab Discard has a keybinding to discard/unload all tabs, but as you said, it doesn't work on some types of pages.

I'm using another extension for that, called “Tab Unloader for Tree Style Tab”. As the name suggests, it's supposed to work in conjunction with “Tree Style Tab”, but it loads and partially works without having to load TST, so you don't need that.
It has keybindings to unload all tabs or the current tab (and a few TST-related ones).

As far as I tested this, it's able to unload those group pages you mentioned (I haven't had much use for them yet, so further testing may be useful).  It also unloads tabs with pages like addons.mozilla.org, which ATD doesn't handle.
There's a small downside to its approach, that is, that the visual cue is not always consistent, sometimes the tabs don't get the little “zZz” to their titles, but they're still being greyed out in Sidebery, which is good enough for me.

> Auto Tab Discard extension. It is better than the standard unload because the keybinding for it actually jumps to the _nearest unloaded tab_, which is awesome.
I honestly hate that is ever does that, because I never want unloaded tabs to be reactivated when I close or unload tabs.
More than half the time, Auto Tab Discard switches to the wrong tab, in my opinion.  Haven't found an appropriate combination of settings that really prevents this.  I like its auto-unload, but avoid manually unloading the active tab with it.
(If anyone knows a “bulletproof” way of keeping a strict “last used tab” sequence, that would be greatly helpful.)
Sorry for that little hijacking here.

**Comment by carlosdoub** [comment]
Thanks for replying and to the author to add a tag.

I have configured keys in sidebery to move around the list, closing or activating.

I think is very valuable to manually unload a tab, and for me usually is not the current tab but others in the list.

For the current tab, it would be fine for me if the next active has the same behavior that after closing it.

Thanks

**Comment by mbnuqw** [comment]
Resolved in v5.0.0
