### ISSUE TITLE
Extra useless padding on bottom of scrollable tab sidebar

### ISSUE THREAD

**Issue by NewsGuyTor** [mbnuqw/sidebery#793]
## Steps to reproduce
Install Sidebery v5.0.0b27, open enough tabs to make the tabs scrollable. 

## Expected behavior
The new tab "+" should be on the bottom even while scrolling

## Actual behavior
There's extra useless white space/padding when you scroll to the bottom of the tabs.

https://user-images.githubusercontent.com/19603024/194756100-752a3b5d-a01d-4567-b41f-136ce1fb4c2b.mp4

### Addon data
<details><code>
{
  "settings": {
    "nativeScrollbars": true,
    "nativeScrollbarsThin": true,
    "nativeScrollbarsLeft": true,
    "selWinScreenshots": false,
    "updateSidebarTitle": true,
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "ctxMenuRenderInact": true,
    "ctxMenuRenderIcons": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": true,
    "navBarSide": "left",
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navActTabsPanelLeftClickAction": "none",
    "navActBookmarksPanelLeftClickAction": "none",
    "navTabsPanelMidClickAction": "none",
    "navBookmarksPanelMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 750,
    "dndExpMod": "none",
    "dndOutside": "win",
    "searchBarMode": "dynamic",
    "warnOnMultiTabClose": "collapsed",
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": false,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsUpdateMark": "all",
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "showNewTabBtns": true,
    "newTabBarPosition": "after_tabs",
    "tabsPanelSwitchActMove": false,
    "tabsUrlInTooltip": "full",
    "openSubPanelOnMouseHover": false,
    "colorizeTabs": false,
    "colorizeTabsSrc": "domain",
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "moveNewTabActivePin": "start",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "colorizeTabsBranches": false,
    "colorizeTabsBranchesSrc": "url",
    "warnOnMultiBookmarkDelete": "collapsed",
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "loadBookmarksOnDemand": true,
    "pinOpenedBookmarksFolder": true,
    "loadHistoryOnDemand": true,
    "fontSize": "s",
    "animations": true,
    "animationSpeed": "norm",
    "theme": "plain",
    "colorScheme": "ff",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollAction": "none",
    "navSwitchPanelsDelay": 128,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "scrollThroughTabsScrollArea": 0,
    "autoMenuMultiSel": true,
    "multipleMiddleClose": false,
    "longClickDelay": 500,
    "wheelThreshold": false,
    "wheelThresholdX": 10,
    "wheelThresholdY": 60,
    "tabDoubleClick": "none",
    "tabsSecondClickActPrev": true,
    "shiftSelAct": true,
    "activateOnMouseUp": false,
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabCloseMiddleClick": "close",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "newTabMiddleClickAction": "new_child",
    "bookmarksLeftClickAction": "open_in_act",
    "bookmarksLeftClickActivate": false,
    "bookmarksLeftClickPos": "default",
    "bookmarksMidClickAction": "open_in_new",
    "bookmarksMidClickActivate": false,
    "bookmarksMidClickPos": "default",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncSaveKeybindings": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "clipboardWrite": true,
    "webRequest": true,
    "webRequestBlocking": true
  },
  "storage": {
    "size": "1.7 mb",
    "props": {
      "containers": "2.19 kb",
      "favDomains": "230 kb",
      "favHashes": "20.4 kb",
      "favicons": "1.42 mb",
      "prevTabsDataCache": "10.8 kb",
      "profileID": "14 b",
      "settings": "3.58 kb",
      "sidebar": "993 b",
      "sidebarCSS": "177 b",
      "tabsDataCache": "10.9 kb",
      "ver": "10 b"
    }
  },
  "sidebar": {
    "panels": {
      "tabs-panel": {
        "type": 2,
        "id": "tabs-panel",
        "name": "len: 4",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "PpbTRs-hB51m": {
        "type": 2,
        "id": "PpbTRs-hB51m",
        "name": "len: 4",
        "color": "toolbar",
        "iconSVG": "icon_tabs",
        "iconIMGSrc": "",
        "iconIMG": "",
        "lockedPanel": false,
        "skipOnSwitching": false,
        "noEmpty": false,
        "newTabCtx": "none",
        "dropTabCtx": "none",
        "moveTabCtx": "none",
        "moveTabCtxNoChild": true,
        "urlRulesActive": false,
        "urlRules": "",
        "bookmarksFolderId": -1,
        "newTabBtns": []
      },
      "history": {
        "type": 4,
        "id": "history",
        "name": "len: 7",
        "color": "toolbar",
        "iconSVG": "icon_clock",
        "tempMode": false,
        "lockedPanel": false,
        "skipOnSwitching": false,
        "viewMode": "history"
      }
    },
    "nav": [
      "tabs-panel",
      "PpbTRs-hB51m",
      "add_tp",
      "sp-UxCjyg8vsuBR",
      "sd-FZ6yG2OjxwBR",
      "search",
      "settings",
      "history"
    ]
  },
  "containers": [
    {
      "id": "firefox-container-1",
      "cookieStoreId": "firefox-container-1",
      "name": "9",
      "icon": "...",
      "color": "blue",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-2",
      "cookieStoreId": "firefox-container-2",
      "name": "6",
      "icon": "...",
      "color": "orange",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-3",
      "cookieStoreId": "firefox-container-3",
      "name": "4",
      "icon": "...",
      "color": "green",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-4",
      "cookieStoreId": "firefox-container-4",
      "name": "8",
      "icon": "...",
      "color": "pink",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-6",
      "cookieStoreId": "firefox-container-6",
      "name": "8",
      "icon": "...",
      "color": "toolbar",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-14",
      "cookieStoreId": "firefox-container-14",
      "name": "2",
      "icon": "...",
      "color": "blue",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-15",
      "cookieStoreId": "firefox-container-15",
      "name": "4",
      "icon": "...",
      "color": "blue",
      "colorCode": "#37adff",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "sidebarCSSLen": "169",
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 47
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 29
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 31
    }
  ],
  "bookmarks": {
    "bookmarksCount": 605,
    "foldersCount": 100,
    "separatorsCount": 0,
    "maxDepth": 5
  }
}
</code></details>

**Comment by emvaized** [comment]
I wouldn't call it useless — it allows to always have some space for performing mouse actions on a tab bar itself (such as middle click to reopen closed tab). But if it really annoys you, perhaps the padding could be removed with some CSS.

**Comment by mbnuqw** [comment]
Custom CSS to remove this padding:
```css
.TabsPanel .container > div > div:last-of-type {
  margin-bottom: 0px;
}
```

**Comment by BensonBear** [comment]
I have tried to do this for a few hours now, cannot get it to work.     
 
I have tried many things, but I assume the correct thing is to go to
Settings > StyleEditor > SideBar

and then add into the right pane the above text, and then restart.  
 
It still has the HORRID space at the bottom that changes as one scrolls the tabs and and down.   To me this renders this entire sophisticated tool useless.  There is no reason whatsoever to REQUIRE this space to be there if one does not want to use it. 
 
I don't know more than beginner CSS, but I determined that I can add style for the tabs for example using  .Tab in this pane.   But the .TabsPanel does not get picked up.   

ETA: I figured out how to inspect the structure of the sidebar using the inspector and I see the TabsPanel  is there, and I guess this complex css constructor is accessing the item styled as a TabsPanel and somehow accessing the last element and saying it should be styled with no margin, but somehow it is not getting to that element. 
 
Maybe there is a typo in the css here, or maybe it is for an older version? 
 
ETA2:  Okay, I see that I can alter the background color of the single item of class TabsPanel with the css

.TabsPanel {
	background-color: #DDDDDD;
}

And I see with the inspector that this item has, eventually, an "animated tab list" which has a list of items the last of which is of class "bottom-space".    
 
I guess there is a reason this item is not styled directly in the css given above, because I tried to style it directly and cannot seem to access it.   Perhaps because it is deeply nested I cannot alter it just by the class name (as I said, I don't know much css but I am trying to get it done anyway). 

ETA3:  Okay, I empirically found that subitems inside other items do not appear to be styled unless the containing items are mentioned in the rule,  so I found that

.TabsPanel .bottom-space { height: 0px;}  

forces that space at the bottom to be of 0 height.   It sort of works for now, but hopefully someone can explain why the correct solution offered above is not working.  (Nor does this work perfectly, as the height is changed again when tabs are deleted).   But at least it is sort of usable for now.

**Comment by Seb35** [comment]
> ```css
> .TabsPanel .bottom-space {
>     height: 0px;
> }
> ```
> 
> forces that space at the bottom to be of 0 height. It sort of works for now, but hopefully someone can explain why the correct solution offered above is not working. (Nor does this work perfectly, as the height is changed again when tabs are deleted). But at least it is sort of usable for now.

Thanks @BensonBear, it works for me on the current version of Sidebery (5.2.0). When viewing the HTML structure in the inspector, there is no node with a class "container", so the rule of @mbnuqw is now ineffective in current version; I guess the structure changed since the date of the comment (2 years ago).

**Comment by BensonBear** [comment]
> Thanks @BensonBear, it works for me on the current version of Sidebery (5.2.0). When viewing the HTML structure in the inspector, there is no node with a class "container", so the rule of @mbnuqw is now ineffective in current version; I guess the structure changed since the date of the comment (2 years ago).

Yes, and I should add that unlike I said (of course) the height is not changed when tabs are deleted, its just that if the tabs are deleted so that there are not enough to fill the space in the scrollarea with the current position of the scrollable items, there will be a space at the bottom, but this space will be filled as soon as one scrolls the scrollable items.   Would be nice to detect this condition and then do the scroll when a tab is deleted, but too much to look into!
