### ISSUE TITLE
Compact sidebar

### ISSUE THREAD

**Issue by daamiian** [mbnuqw/sidebery#867]
## Description

Sidebar consisting only of panels vertically oriented, without the tab list. Clicking on a panel expands the sidebar as normal, showing the tabs. The benefit is that the user may add mouse button bindings for the panels to quickly open new tabs in specific panels without having to open the whole sidebar, among other bindings. 

Side-note, to use keyboard bindings, you need to open the panel first with F1, but with this option, the user can keep the panel open all the time without sacrificing screen space, and use all of the keybindings without first opening the sidebar.

**Comment by mbnuqw** [comment]
Unfortunately, it's not possible from Sidebery due to the API limitations - addons cannot change the size of sidebar and cannot open/close sidebar without explicit user action (click or pressing keybinding shortcut).

This is possible only with [userChrome.css hacks](https://www.reddit.com/r/FirefoxCSS/search?q=hide+sidebar&restrict_sr=on&sort=relevance&t=all)
