### ISSUE TITLE
Hide Sidebery Logo

### ISSUE THREAD

**Issue by davidleejy** [mbnuqw/sidebery#929]
Can the logo be hidden to free up some space?

<img width="323" alt="Screenshot 2023-02-06 at 10 51 01 PM" src="https://user-images.githubusercontent.com/1690072/217004009-24481cba-e837-4df8-bcc6-751f67b7efa7.png">

**Comment by shazzap** [comment]
You can achieve this by adding the following to your userChrome.css file.

#sidebar-header {
  display: none !important;
}

**Comment by davidleejy** [comment]
Does anyone know if there is some sort of reason for this not being a part of Sidebery's settings :) ?

**Comment by shazzap** [comment]
It may not be possible. Because that is the firefox sidebar header element, not just the sidebery heading. By removing it you can no longer select other Firefox sidebars (history, bookmarks) and other side bar options (move sidebar to left, right ...)

I'd be suprised if Firefox's API allowed for that. Same issue in that you have to unfortunately resort to CSS to hide Firefox's normal horizontal tabs, because the ability to do so is not provided for via the API.

**Comment by emvaized** [comment]
@davidleejy 
Because it is part of Firefox interface itself, not the Sidebery. Therefore, this question should be better addressed to Firefox team

**Comment by davidleejy** [comment]
Thanks for weighing in @shazzap @emvaized .
