### ISSUE TITLE
Colorize tabs

### ISSUE THREAD

**Issue by TheSwingingStar** [mbnuqw/sidebery#93]
## Description 
I'd like to be able to set the `margin`, `padding`, and `border-radius` properties of tabs.

For a more complex idea, I'd like an option to set the tab coloring based on the domain of the tab, be it based on the favicon's colors, or a derived value from the domain itself, whatever more easily achievable

**Comment by mbnuqw** [comment]
To be honest, I don't want to increase count of custom css variables anymore, because they slow down updating styles and add extra complexity for creating new themes. Also, some styles (tab/bookmarks height) are used for now in calculations, so there is no simple way to add margin (this, though, will be fixed later).

Instead, you can use custom css for more precise personalization in Settings / Styles editor (the right side text field). 
To get currently available css-selectors use debugger:
- enter about:debugging in the URL bar.
- in the left-hand menu, click This Firefox (or This Nightly).
- click Inspect next to Sidebery extension.
- select frame to inspect - click on the rectangular icon (with three sections) in top-right area of the debugger page and select "/sidebar/index.html"
- browse "Inspector" tab
[more info](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging)

For example, to change border radius and add margin for tabs in Tactile theme check out this css:
```css
#root {
  --tabs-height: 32px;
}

.Tab:before {
  top: 2px;
  height: 29px;
  border-top-left-radius: 8px;
  border-bottom-left-radius: 8px;
}
```
![screenshot-2019 09 23-19 15 30_001](https://user-images.githubusercontent.com/6276694/65433650-daaecd80-de36-11e9-8df1-599f8aeb880d.png)

---

About tabs coloring - this is a nice idea. I think I can read special tag "theme-color" to get brand color of a page (this will require Websites data permission though) and then provide this value to styles via css var.

ps. I'll change title of this issue to express this feature.

**Comment by tradewatcher** [comment]
I understand your opinion about increase of css variables. But in my opinion you entered several useless variables and miss the important ones. Especially the Tab css need several important upgrades.

CSS of discarded, unread, read, actually selected are more important parts to reach high customization and improve workflow.

CSS options for margin, padding, and border-radius of tabs will make the difference for desktop/mobile and personal preferences.
The possibility to colorize a specific domain-based tab is more special but also understandable if u have to open a domain very often.

While nobody care of the configuration css as example. 

But thanks for your good job anyway!

**Comment by moapwr** [comment]
highlighting of unread tabs would be very useful to me, same as having an option to adjust marings and paddings of the tab-list/grid for ppl have different pixel density and quality of eyesight.

**Comment by mbnuqw** [comment]
Closing as implemented in v5.
