### ISSUE TITLE
Keybinding to rename the title of a tab

### ISSUE THREAD

**Issue by FabianoLothor** [mbnuqw/sidebery#966]
## Description

Title is self-explanatory

**Comment by prmichaelsen** [comment]
Can you already rename the title of a tab? I've been trying to find how to do that.

**Comment by prmichaelsen** [comment]
#185 in final beta

**Comment by JohnVKRDam** [comment]
Is there any chance this will get implemented? I do Tab renames a LOT and I would really love to be able to use F2 (or another key or key-combo) to start the Edit Title Context Menu option. It would be so much easier to use compared to right-clicking through the Context Menu.

**Comment by JohnVKRDam** [comment]
Over 7 months have past since my last post in this thread. Is this still something that's going to happen at some point?  :)

I am not knocking you for not having done this, in any way! I really do understand how much work it is to maintain and expand this AMAZING extension as it is. It's just that this option would be so, SO extremely useful to have, that I am willing to literally fall to my knees and beg you to add it  ;)  LOL

I can also assure you that the number of participants in the thread does not (even a little bit) reflect the actual number of people that would LOVE to see this implemented.

Okay, so, I have dropped to my knees. Shall I start begging now? ... :p
